export const GameBalance = {
  movement: {
    acceleration: 48,
    deceleration: 72,
    turnResponsiveness: 16,
    arrivalRadius: 0.22,
    holdReleaseThresholdMs: 170,
    dodgeDistance: 5.1,
    dodgeDuration: 0.22,
    dodgeCooldown: 1.25,
    dodgeInvulnerabilityDuration: 0.20,
    jumpVelocity: 7.9,
    gravity: 19.5,
    landingVelocityThreshold: -4.5,
    stepHeight: 0.22,
    maximumJumpOntoHeight: 1.15,
    maximumWalkableSlopeDegrees: 42,
    groundSnapDistance: 0.18,
    minX: -37.0,
    maxX: 37.0,
    minZ: -25.0,
    maxZ: 145.0,
  },
  worldVolumes: {
    shallowWaterSpeedMultiplier: 0.65,
    deepWaterSpeedMultiplier: 0.25,
    drownSeconds: 5,
  },
  camera: {
    followSharpness: 8.5,
    lookAheadDistance: 1.35,
    lookAheadSharpness: 5.5,
    idleRadius: 23,
    movingRadius: 24.4,
    zoomSharpness: 3.8,
    movementSpeedForFullZoom: 7.5,
  },
  combat: {
    lightHitStopSeconds: 0.018,
    heavyHitStopSeconds: 0.045,
    reactionHitStopSeconds: 0.065,
    enemyFlashSeconds: 0.075,
    lightKnockbackSpeed: 3.2,
    heavyKnockbackSpeed: 6.0,
    knockbackDecay: 14,
    damageNumberLifetimeSeconds: 0.72,
    damageNumberRiseSpeed: 46,
    playerHitInvulnerabilitySeconds: 0.55,
    playerHitFlashSeconds: 0.18,
    enemyWindupSeconds: 0.52,
    enemyRecoverySeconds: 0.46,
    eliteWindupSeconds: 0.72,
    eliteRecoverySeconds: 0.60,
    enemyAttackRange: 1.35,
    telegraphRadius: 1.5,
    eliteTelegraphRadius: 2.1,
    cameraShakeLight: 0.08,
    cameraShakeHeavy: 0.18,
    cameraShakeReaction: 0.28,
  },
  debug: {
    enabled: true,
    updateIntervalSeconds: 0.1,
  },
} as const;
