import type {
  ActorDefinition,
  ActorVisualProfile,
  InteractionProfile,
} from '../../actors';

export const actorVisualProfiles: readonly ActorVisualProfile[] = [
  {
    id: 'actor.human.hunter',
    primitive: 'capsule',
    scale: 1,
    height: 1.8,
    highlightIntensity: 0.45,
    promptOffset: 2.15,
  },
  {
    id: 'actor.human.merchant',
    primitive: 'capsule',
    scale: 1,
    height: 1.75,
    highlightIntensity: 0.45,
    promptOffset: 2.1,
  },
  {
    id: 'actor.human.captain',
    primitive: 'capsule',
    scale: 1,
    height: 1.85,
    highlightIntensity: 0.45,
    promptOffset: 2.2,
  },
  {
    id: 'actor.human.elder',
    primitive: 'capsule',
    scale: 0.96,
    height: 1.7,
    highlightIntensity: 0.45,
    promptOffset: 2.05,
  },
  {
    id: 'actor.human.blacksmith',
    primitive: 'capsule',
    scale: 1.08,
    height: 1.9,
    highlightIntensity: 0.45,
    promptOffset: 2.25,
  },
];

export const interactionProfiles: readonly InteractionProfile[] = [
  {
    id: 'interaction.talk',
    promptVerb: 'Speak to',
    range: 2.3,
    priority: 10,
    highlightMode: 'outline',
  },
  {
    id: 'interaction.trade',
    promptVerb: 'Trade with',
    range: 2.3,
    priority: 12,
    highlightMode: 'outline',
  },
  {
    id: 'interaction.travel',
    promptVerb: 'Travel with',
    range: 2.6,
    priority: 11,
    highlightMode: 'glow',
    disabledPrompt: 'Route unavailable',
  },
];

export const actorDefinitions: readonly ActorDefinition[] = [
  {
    id: 'actor.hunter-mara',
    displayName: 'Hunter Mara',
    roleTags: ['quest-giver', 'hunter', 'story'],
    position: { x: -4, y: 0, z: 6 },
    visualProfileId: 'actor.human.hunter',
    interactionProfileId: 'interaction.talk',
    persistentId: 'npc.hunter-mara',
    components: [
      { type: 'interaction', definitionId: 'interaction.talk' },
      { type: 'dialogue', definitionId: 'dialogue.hunter-mara' },
      { type: 'quest', definitionId: 'quest.wolf-problem' },
      { type: 'ambient', definitionId: 'ambient.hunter' },
      { type: 'save', definitionId: 'save.actor-default' },
    ],
  },
  {
    id: 'actor.camp-merchant',
    displayName: 'Camp Merchant',
    roleTags: ['merchant', 'supplies'],
    position: { x: 4, y: 0, z: 6 },
    visualProfileId: 'actor.human.merchant',
    interactionProfileId: 'interaction.trade',
    persistentId: 'npc.camp-merchant',
    components: [
      { type: 'interaction', definitionId: 'interaction.trade' },
      { type: 'dialogue', definitionId: 'dialogue.camp-merchant' },
      { type: 'merchant', definitionId: 'merchant.camp-supplies' },
      { type: 'ambient', definitionId: 'ambient.merchant' },
      { type: 'save', definitionId: 'save.actor-default' },
    ],
  },
  {
    id: 'actor.ferry-captain',
    displayName: 'Ferry Captain',
    roleTags: ['transport', 'story'],
    position: { x: 8, y: 0, z: -3 },
    visualProfileId: 'actor.human.captain',
    interactionProfileId: 'interaction.travel',
    persistentId: 'npc.ferry-captain',
    components: [
      { type: 'interaction', definitionId: 'interaction.travel' },
      { type: 'dialogue', definitionId: 'dialogue.ferry-captain' },
      { type: 'transport', definitionId: 'transport.forest-ferry' },
      { type: 'ambient', definitionId: 'ambient.captain' },
      { type: 'save', definitionId: 'save.actor-default' },
    ],
  },
  {
    id: 'actor.village-elder',
    displayName: 'Village Elder',
    roleTags: ['story', 'quest-giver'],
    position: { x: -7, y: 0, z: -2 },
    visualProfileId: 'actor.human.elder',
    interactionProfileId: 'interaction.talk',
    persistentId: 'npc.village-elder',
    components: [
      { type: 'interaction', definitionId: 'interaction.talk' },
      { type: 'dialogue', definitionId: 'dialogue.village-elder' },
      { type: 'quest', definitionId: 'quest.main-introduction' },
      { type: 'save', definitionId: 'save.actor-default' },
    ],
  },
  {
    id: 'actor.blacksmith',
    displayName: 'Blacksmith Orin',
    roleTags: ['merchant', 'blacksmith', 'crafting-future'],
    position: { x: 1, y: 0, z: -7 },
    visualProfileId: 'actor.human.blacksmith',
    interactionProfileId: 'interaction.trade',
    persistentId: 'npc.blacksmith-orin',
    components: [
      { type: 'interaction', definitionId: 'interaction.trade' },
      { type: 'dialogue', definitionId: 'dialogue.blacksmith' },
      { type: 'merchant', definitionId: 'merchant.blacksmith' },
      { type: 'ambient', definitionId: 'ambient.blacksmith' },
      { type: 'save', definitionId: 'save.actor-default' },
    ],
  },
];
