import type { CharacterSkillTreeDefinition, SkillNodeDefinition, SkillPassiveModifier, SkillPathDefinition, SkillNodeRole } from './SkillTreeTypes';
type Branch = SkillNodeDefinition['branch'];
const RING_COST = { 1: 1, 2: 2, 3: 3, 4: 4 } as const;
const RING_LEVEL = { 1: 2, 2: 4, 3: 7, 4: 12 } as const;
const node = (characterId: string, pathId: string, id: string, name: string, description: string, kind: SkillNodeDefinition['kind'], role: SkillNodeRole, branch: Branch, ring: 1|2|3|4, sector: number, abilityId?: string, passiveModifier?: SkillPassiveModifier, prerequisites: readonly string[] = [], pathPointsRequired = 0): SkillNodeDefinition => ({ id: `${characterId}.${id}`, characterId, name, description, kind, role, abilityId, passiveModifier, cost: role === 'ultimate' ? 6 : role === 'advanced-skill' ? 4 : RING_COST[ring], minimumLevel: role === 'ultimate' ? 22 : RING_LEVEL[ring], prerequisiteNodeIds: prerequisites.map(value => `${characterId}.${value}`), connectedNodeIds: prerequisites.map(value => `${characterId}.${value}`), pathId, pathPointsRequired, isUltimate: role === 'ultimate', branch, tier: ring, ring, sector });
const path = (id: string, name: string, summary: string, branch: Branch): SkillPathDefinition => ({ id, name, summary, branch });

export const characterSkillTrees: readonly CharacterSkillTreeDefinition[] = [
  {
    characterId: 'vanguard', identityTitle: 'Warrior', identitySummary: 'A durable front-line fighter who can specialize in raw power, protection, or relentless momentum.', combatStyle: 'Close-range bruiser · stagger · survival',
    strengths: ['Highest durability', 'Strong stagger', 'Flexible front-line roles'],
    paths: [
      path('power', 'Power', 'Heavy attacks, stagger, and finishing pressure', 'assault'),
      path('guard', 'Guard', 'Health, mitigation, threat control, and party protection', 'survival'),
      path('momentum', 'Momentum', 'Charges, attack rhythm, forward movement, and pressure', 'control'),
    ],
    nodes: [
      node('vanguard', 'power', 'cleave', 'Cleave', 'A broad forward swing that hits multiple enemies.', 'active', 'standard-skill', 'assault', 1, 0, 'ability.melee-cleave', undefined, [], 0),
      node('vanguard', 'power', 'forceful-blows', 'Forceful Blows', 'Increase melee stagger and slightly improve melee damage.', 'passive', 'support', 'assault', 2, 0, undefined, { meleeDamagePercent: 0.06, staggerPower: 0.12 }, ['cleave'], 0),
      node('vanguard', 'power', 'heavy-hand', 'Heavy Hand', 'Cleave becomes slower but gains damage and guard-breaking force.', 'upgrade', 'support', 'assault', 2, 1, undefined, undefined, ['cleave'], 0),
      node('vanguard', 'power', 'ground-breaker', 'Ground Breaker', 'Slam the ground to damage and stagger enemies around the impact.', 'active', 'advanced-skill', 'assault', 3, 0, 'ability.heavy-slam', undefined, ['forceful-blows'], 0),
      node('vanguard', 'power', 'crushing-impact', 'Crushing Impact', 'Heavy skills deal increased stagger and armor damage.', 'passive', 'support', 'assault', 3, 1, undefined, { staggerPower: 0.18 }, ['forceful-blows'], 0),
      node('vanguard', 'power', 'executioner', 'Executioner', 'Deal increased damage to enemies below one-third health.', 'passive', 'support', 'assault', 3, 2, undefined, { meleeDamagePercent: 0.08 }, ['heavy-hand'], 0),
      node('vanguard', 'power', 'overpower', 'Overpower', 'Deliver a devastating committed strike with extreme stagger.', 'active', 'ultimate', 'assault', 4, 0, 'ability.spin-attack', undefined, ['ground-breaker', 'crushing-impact'], 15),
      node('vanguard', 'power', 'seismic-cleave', 'Seismic Cleave', 'Cleave releases a short forward shockwave.', 'upgrade', 'support', 'assault', 4, 1, undefined, undefined, ['ground-breaker'], 0),
      node('vanguard', 'power', 'blood-momentum', 'Blood Momentum', 'Defeating an enemy briefly increases attack speed.', 'passive', 'support', 'assault', 4, 2, undefined, { attackSpeedPercent: 0.12 }, ['crushing-impact'], 0),
      node('vanguard', 'power', 'unrelenting-force', 'Unrelenting Force', 'Staggering an enemy empowers the next damaging skill.', 'passive', 'support', 'assault', 4, 3, undefined, { meleeDamagePercent: 0.1 }, ['executioner'], 0),
      node('vanguard', 'guard', 'brace', 'Brace', 'Brace against incoming damage and resist interruption.', 'active', 'standard-skill', 'survival', 1, 1, 'ability.barrier', undefined, [], 0),
      node('vanguard', 'guard', 'hardened', 'Hardened', 'Increase maximum health.', 'passive', 'support', 'survival', 2, 2, undefined, { maximumHealth: 2 }, ['brace'], 0),
      node('vanguard', 'guard', 'iron-skin', 'Iron Skin', 'Increase armor and stagger resistance.', 'passive', 'support', 'survival', 2, 3, undefined, { armor: 0.15, staggerResistance: 0.08 }, ['brace'], 0),
      node('vanguard', 'guard', 'guardian-roar', 'Guardian Roar', 'Challenge nearby enemies and gain temporary protection.', 'active', 'advanced-skill', 'survival', 3, 3, 'ability.shield', undefined, ['hardened'], 0),
      node('vanguard', 'guard', 'second-wind', 'Second Wind', 'Recover more quickly after avoiding damage.', 'passive', 'support', 'survival', 3, 4, undefined, { cooldownRatePercent: 0.08 }, ['hardened'], 0),
      node('vanguard', 'guard', 'steadfast', 'Steadfast', 'Reduce interruption and knockback from enemy attacks.', 'passive', 'support', 'survival', 3, 5, undefined, { staggerResistance: 0.15 }, ['iron-skin'], 0),
      node('vanguard', 'guard', 'living-bulwark', 'Living Bulwark', 'Create a powerful defensive aura that protects nearby allies.', 'active', 'ultimate', 'survival', 4, 4, 'ability.barrier', undefined, ['guardian-roar', 'second-wind'], 15),
      node('vanguard', 'guard', 'fortified-brace', 'Fortified Brace', 'Brace lasts longer and protects from every direction.', 'upgrade', 'support', 'survival', 4, 5, undefined, undefined, ['guardian-roar'], 0),
      node('vanguard', 'guard', 'last-stand', 'Last Stand', 'Gain strong protection while at low health.', 'passive', 'support', 'survival', 4, 6, undefined, { armor: 0.25 }, ['second-wind'], 0),
      node('vanguard', 'guard', 'shared-protection', 'Shared Protection', 'A portion of gained shielding is shared with nearby allies.', 'passive', 'support', 'survival', 4, 7, undefined, { maximumHealth: 1 }, ['steadfast'], 0),
      node('vanguard', 'momentum', 'vanguard-charge', 'Vanguard Charge', 'Rush forward and impact enemies in the destination lane.', 'active', 'standard-skill', 'control', 1, 2, 'ability.charge', undefined, [], 0),
      node('vanguard', 'momentum', 'forward-pressure', 'Forward Pressure', 'Moving toward enemies slightly increases movement speed.', 'passive', 'support', 'control', 2, 4, undefined, { movementSpeed: 0.12 }, ['vanguard-charge'], 0),
      node('vanguard', 'momentum', 'quick-recovery', 'Quick Recovery', 'Reduce dodge cooldown.', 'passive', 'support', 'control', 2, 5, undefined, { dodgeCooldownPercent: 0.1 }, ['vanguard-charge'], 0),
      node('vanguard', 'momentum', 'warpath', 'Warpath', 'Enter a short aggressive surge of speed and attack tempo.', 'active', 'advanced-skill', 'control', 3, 6, 'ability.dash', undefined, ['forward-pressure'], 0),
      node('vanguard', 'momentum', 'driving-strike', 'Driving Strike', 'Basic attacks step the Warrior forward.', 'upgrade', 'support', 'control', 3, 7, undefined, undefined, ['forward-pressure'], 0),
      node('vanguard', 'momentum', 'battle-rhythm', 'Battle Rhythm', 'Consecutive basic attacks gradually increase attack speed.', 'passive', 'support', 'control', 3, 8, undefined, { attackSpeedPercent: 0.1 }, ['quick-recovery'], 0),
      node('vanguard', 'momentum', 'juggernaut', 'Juggernaut', 'Become an unstoppable advancing force while continuously attacking.', 'active', 'ultimate', 'control', 4, 8, 'ability.leap', undefined, ['warpath', 'driving-strike'], 15),
      node('vanguard', 'momentum', 'relentless-charge', 'Relentless Charge', 'Vanguard Charge passes through weaker enemies.', 'upgrade', 'support', 'control', 4, 9, undefined, undefined, ['warpath'], 0),
      node('vanguard', 'momentum', 'no-retreat', 'No Retreat', 'Dodging toward an enemy empowers the next melee hit.', 'passive', 'support', 'control', 4, 10, undefined, { meleeDamagePercent: 0.08 }, ['driving-strike'], 0),
      node('vanguard', 'momentum', 'unstoppable', 'Unstoppable', 'Movement skills grant temporary stagger resistance.', 'passive', 'support', 'control', 4, 11, undefined, { staggerResistance: 0.12 }, ['battle-rhythm'], 0),
    ],
  },
  {
    characterId: 'tempest', identityTitle: 'Rogue', identitySummary: 'A fast melee specialist built around precision, mobility, and deceptive status pressure.', combatStyle: 'Burst · mobility · precision',
    strengths: ['Fastest attacks', 'Strong repositioning', 'High single-target pressure'],
    paths: [
      path('precision', 'Precision', 'Critical timing, repeated strikes, and execution', 'assault'),
      path('mobility', 'Mobility', 'Dashes, flanking, evasive chains, and attack flow', 'control'),
      path('trickery', 'Trickery', 'Poison, smoke, debuffs, and disengagement', 'survival'),
    ],
    nodes: [
      node('tempest', 'precision', 'lunging-strike', 'Lunging Strike', 'Lunge forward with a precise extended stab.', 'active', 'standard-skill', 'assault', 1, 0, 'ability.melee-strike', undefined, [], 0),
      node('tempest', 'precision', 'keen-edge', 'Keen Edge', 'Increase attack damage slightly.', 'passive', 'support', 'assault', 2, 0, undefined, { attack: 0.08 }, ['lunging-strike'], 0),
      node('tempest', 'precision', 'measured-cuts', 'Measured Cuts', 'Repeated hits against one target build damage.', 'upgrade', 'support', 'assault', 2, 1, undefined, undefined, ['lunging-strike'], 0),
      node('tempest', 'precision', 'twin-fang', 'Twin Fang', 'Deliver two rapid focused strikes.', 'active', 'advanced-skill', 'assault', 3, 0, 'ability.melee-cleave', undefined, ['keen-edge'], 0),
      node('tempest', 'precision', 'exploit-opening', 'Exploit Opening', 'Deal increased damage to staggered or controlled enemies.', 'passive', 'support', 'assault', 3, 1, undefined, { meleeDamagePercent: 0.08 }, ['keen-edge'], 0),
      node('tempest', 'precision', 'deadly-precision', 'Deadly Precision', 'Precision effects gain stronger finishing damage.', 'passive', 'support', 'assault', 3, 2, undefined, { attack: 0.1 }, ['measured-cuts'], 0),
      node('tempest', 'precision', 'assassinate', 'Assassinate', 'A devastating strike against isolated or weakened enemies.', 'active', 'ultimate', 'assault', 4, 0, 'ability.heavy-slam', undefined, ['twin-fang', 'exploit-opening'], 15),
      node('tempest', 'precision', 'piercing-lunge', 'Piercing Lunge', 'Lunging Strike passes through the first enemy.', 'upgrade', 'support', 'assault', 4, 1, undefined, undefined, ['twin-fang'], 0),
      node('tempest', 'precision', 'perfect-timing', 'Perfect Timing', 'A last-moment dodge empowers the next attack.', 'passive', 'support', 'assault', 4, 2, undefined, { meleeDamagePercent: 0.1 }, ['exploit-opening'], 0),
      node('tempest', 'precision', 'death-marks', 'Death Marks', 'Repeated strikes build marks that burst at maximum stacks.', 'passive', 'support', 'assault', 4, 3, undefined, { attackSpeedPercent: 0.08 }, ['deadly-precision'], 0),
      node('tempest', 'mobility', 'dash-strike', 'Dash Strike', 'Dash through a target and attack from the opposite side.', 'active', 'standard-skill', 'control', 1, 1, 'ability.dash', undefined, [], 0),
      node('tempest', 'mobility', 'lightfoot', 'Lightfoot', 'Increase movement speed.', 'passive', 'support', 'control', 2, 2, undefined, { movementSpeed: 0.18 }, ['dash-strike'], 0),
      node('tempest', 'mobility', 'evasive-form', 'Evasive Form', 'Increase dodge availability.', 'passive', 'support', 'control', 2, 3, undefined, { dodgeCooldownPercent: 0.12 }, ['dash-strike'], 0),
      node('tempest', 'mobility', 'backstep-slash', 'Backstep Slash', 'Strike while retreating out of melee range.', 'active', 'advanced-skill', 'control', 3, 3, 'ability.retreat', undefined, ['lightfoot'], 0),
      node('tempest', 'mobility', 'flow-state', 'Flow State', 'Using an ability accelerates dodge recovery.', 'passive', 'support', 'control', 3, 4, undefined, { cooldownRatePercent: 0.08 }, ['lightfoot'], 0),
      node('tempest', 'mobility', 'flanking-step', 'Flanking Step', 'Attacks from the side or rear deal increased damage.', 'upgrade', 'support', 'control', 3, 5, undefined, undefined, ['evasive-form'], 0),
      node('tempest', 'mobility', 'phantom-rhythm', 'Phantom Rhythm', 'Chain rapid phasing attacks through nearby targets.', 'active', 'ultimate', 'control', 4, 4, 'ability.blink', undefined, ['backstep-slash', 'flow-state'], 15),
      node('tempest', 'mobility', 'double-dash', 'Double Dash', 'Dash Strike gains an additional charge.', 'upgrade', 'support', 'control', 4, 5, undefined, undefined, ['backstep-slash'], 0),
      node('tempest', 'mobility', 'untouchable', 'Untouchable', 'Avoiding several attacks grants attack speed.', 'passive', 'support', 'control', 4, 6, undefined, { attackSpeedPercent: 0.14 }, ['flow-state'], 0),
      node('tempest', 'mobility', 'momentum-recovery', 'Momentum Recovery', 'Mobility skills improve cooldown recovery.', 'passive', 'support', 'control', 4, 7, undefined, { cooldownRatePercent: 0.1 }, ['flanking-step'], 0),
      node('tempest', 'trickery', 'poison-blade', 'Poison Blade', 'Coat the next attacks with a lingering poison effect.', 'active', 'standard-skill', 'survival', 1, 2, 'ability.poison-cloud', undefined, [], 0),
      node('tempest', 'trickery', 'dirty-fighting', 'Dirty Fighting', 'Basic attacks occasionally weaken enemies.', 'passive', 'support', 'survival', 2, 4, undefined, { attack: 0.05 }, ['poison-blade'], 0),
      node('tempest', 'trickery', 'lingering-venom', 'Lingering Venom', 'Poison effects last longer and deal more damage.', 'passive', 'support', 'survival', 2, 5, undefined, { meleeDamagePercent: 0.06 }, ['poison-blade'], 0),
      node('tempest', 'trickery', 'smoke-bomb', 'Smoke Bomb', 'Create a cloud that disrupts enemy targeting and enables escape.', 'active', 'advanced-skill', 'survival', 3, 6, 'ability.ground-fire', undefined, ['dirty-fighting'], 0),
      node('tempest', 'trickery', 'opportunist', 'Opportunist', 'Deal bonus damage to poisoned or controlled targets.', 'passive', 'support', 'survival', 3, 7, undefined, { meleeDamagePercent: 0.09 }, ['dirty-fighting'], 0),
      node('tempest', 'trickery', 'toxic-recovery', 'Toxic Recovery', 'Damaging poisoned enemies improves ability recovery.', 'passive', 'support', 'survival', 3, 8, undefined, { cooldownRatePercent: 0.09 }, ['lingering-venom'], 0),
      node('tempest', 'trickery', 'master-of-deception', 'Master of Deception', 'Vanish and return with a massively empowered opening attack.', 'active', 'ultimate', 'survival', 4, 8, 'ability.blink', undefined, ['smoke-bomb', 'opportunist'], 15),
      node('tempest', 'trickery', 'virulent-poison', 'Virulent Poison', 'Poison spreads when an affected enemy is defeated.', 'upgrade', 'support', 'survival', 4, 9, undefined, undefined, ['smoke-bomb'], 0),
      node('tempest', 'trickery', 'smoke-escape', 'Smoke Escape', 'Entering Smoke Bomb immediately breaks enemy pursuit.', 'upgrade', 'support', 'survival', 4, 10, undefined, undefined, ['opportunist'], 0),
      node('tempest', 'trickery', 'hidden-opening', 'Hidden Opening', 'Attacks made after disengaging gain damage and stagger.', 'passive', 'support', 'survival', 4, 11, undefined, { attack: 0.12, staggerPower: 0.08 }, ['toxic-recovery'], 0),
    ],
  },
  {
    characterId: 'hunter-mara', identityTitle: 'Hunter', identitySummary: 'A physical ranged specialist who chooses between marksmanship, prepared traps, and survival tools.', combatStyle: 'Ranged precision · traps · survival',
    strengths: ['Safe physical damage', 'Battlefield preparation', 'Reliable disengagement'],
    paths: [
      path('marksmanship', 'Marksmanship', 'Range, penetration, and priority-target damage', 'assault'),
      path('traps', 'Traps', 'Roots, explosions, battlefield zones, and preparation', 'control'),
      path('survival', 'Survival', 'Retreat, recovery, awareness, and exploration safety', 'survival'),
    ],
    nodes: [
      node('hunter-mara', 'marksmanship', 'power-shot', 'Power Shot', 'Fire a slower, stronger projectile through the target lane.', 'active', 'standard-skill', 'assault', 1, 0, 'ability.piercing-shot', undefined, [], 0),
      node('hunter-mara', 'marksmanship', 'steady-aim', 'Steady Aim', 'Increase projectile damage and effective range.', 'passive', 'support', 'assault', 2, 0, undefined, { projectileDamagePercent: 0.07 }, ['power-shot'], 0),
      node('hunter-mara', 'marksmanship', 'quick-draw', 'Quick Draw', 'Increase the speed of basic ranged attacks.', 'upgrade', 'support', 'assault', 2, 1, undefined, { attackSpeedPercent: 0.08 }, ['power-shot'], 0),
      node('hunter-mara', 'marksmanship', 'marked-target', 'Marked Target', 'Mark a priority target to amplify Hunter damage against it.', 'active', 'advanced-skill', 'assault', 3, 0, 'ability.magic-missile', undefined, ['steady-aim'], 0),
      node('hunter-mara', 'marksmanship', 'long-range-hunter', 'Long-Range Hunter', 'Deal increased damage from longer distances.', 'passive', 'support', 'assault', 3, 1, undefined, { projectileDamagePercent: 0.09 }, ['steady-aim'], 0),
      node('hunter-mara', 'marksmanship', 'piercing-shots', 'Piercing Shots', 'Physical projectiles gain penetration against grouped enemies.', 'upgrade', 'support', 'assault', 3, 2, undefined, undefined, ['quick-draw'], 0),
      node('hunter-mara', 'marksmanship', 'deadeye', 'Deadeye', 'Enter a precision state and unleash lethal long-range shots.', 'active', 'ultimate', 'assault', 4, 0, 'ability.spread-shot', undefined, ['marked-target', 'long-range-hunter'], 15),
      node('hunter-mara', 'marksmanship', 'charged-shot', 'Charged Shot', 'Power Shot may be charged for damage and penetration.', 'upgrade', 'support', 'assault', 4, 1, undefined, undefined, ['marked-target'], 0),
      node('hunter-mara', 'marksmanship', 'perfect-shot', 'Perfect Shot', 'Repeated hits against one target increase projectile damage.', 'passive', 'support', 'assault', 4, 2, undefined, { projectileDamagePercent: 0.1 }, ['long-range-hunter'], 0),
      node('hunter-mara', 'marksmanship', 'target-exploitation', 'Target Exploitation', 'Marked targets take additional damage from all Hunter skills.', 'passive', 'support', 'assault', 4, 3, undefined, { attack: 0.08 }, ['piercing-shots'], 0),
      node('hunter-mara', 'traps', 'snare-trap', 'Snare Trap', 'Place a trap that roots or heavily slows the first enemy.', 'active', 'standard-skill', 'control', 1, 1, 'ability.frost-nova', undefined, [], 0),
      node('hunter-mara', 'traps', 'field-preparation', 'Field Preparation', 'Improve trap duration and deployment recovery.', 'passive', 'support', 'control', 2, 2, undefined, { cooldownRatePercent: 0.07 }, ['snare-trap'], 0),
      node('hunter-mara', 'traps', 'barbed-snare', 'Barbed Snare', 'Snared enemies take damage when attempting to move.', 'upgrade', 'support', 'control', 2, 3, undefined, undefined, ['snare-trap'], 0),
      node('hunter-mara', 'traps', 'blast-trap', 'Blast Trap', 'Place an explosive trap that damages nearby enemies.', 'active', 'advanced-skill', 'control', 3, 3, 'ability.ground-fire', undefined, ['field-preparation'], 0),
      node('hunter-mara', 'traps', 'concussive-charge', 'Concussive Charge', 'Blast Trap gains knockback and stagger.', 'upgrade', 'support', 'control', 3, 4, undefined, undefined, ['field-preparation'], 0),
      node('hunter-mara', 'traps', 'trap-network', 'Trap Network', 'Increase the number of traps that may remain active.', 'passive', 'support', 'control', 3, 5, undefined, { cooldownRatePercent: 0.08 }, ['barbed-snare'], 0),
      node('hunter-mara', 'traps', 'master-trapper', 'Master Trapper', 'Deploy a coordinated trap field that controls a large area.', 'active', 'ultimate', 'control', 4, 4, 'ability.poison-cloud', undefined, ['blast-trap', 'concussive-charge'], 15),
      node('hunter-mara', 'traps', 'chain-reaction', 'Chain Reaction', 'Triggering one trap accelerates the others.', 'passive', 'support', 'control', 4, 5, undefined, { cooldownRatePercent: 0.12 }, ['blast-trap'], 0),
      node('hunter-mara', 'traps', 'ambush-ground', 'Ambush Ground', 'Trapped enemies take increased projectile damage.', 'passive', 'support', 'control', 4, 6, undefined, { projectileDamagePercent: 0.1 }, ['concussive-charge'], 0),
      node('hunter-mara', 'traps', 'rearming-mechanism', 'Rearming Mechanism', 'Traps automatically rearm once after triggering.', 'upgrade', 'support', 'control', 4, 7, undefined, undefined, ['trap-network'], 0),
      node('hunter-mara', 'survival', 'retreating-shot', 'Retreating Shot', 'Leap backward while firing at the nearest threat.', 'active', 'standard-skill', 'survival', 1, 2, 'ability.retreat', undefined, [], 0),
      node('hunter-mara', 'survival', 'trailwise', 'Trailwise', 'Increase movement speed and resist slowing effects.', 'passive', 'support', 'survival', 2, 4, undefined, { movementSpeed: 0.15 }, ['retreating-shot'], 0),
      node('hunter-mara', 'survival', 'field-dressing', 'Field Dressing', 'Improve recovery between encounters.', 'passive', 'support', 'survival', 2, 5, undefined, { maximumHealth: 1 }, ['retreating-shot'], 0),
      node('hunter-mara', 'survival', 'camouflage', 'Camouflage', 'Reduce enemy awareness and empower the next ranged attack.', 'active', 'advanced-skill', 'survival', 3, 6, 'ability.blink', undefined, ['trailwise'], 0),
      node('hunter-mara', 'survival', 'predator-awareness', 'Predator Awareness', 'Improve damage against nearby revealed threats.', 'passive', 'support', 'survival', 3, 7, undefined, { attack: 0.06 }, ['trailwise'], 0),
      node('hunter-mara', 'survival', 'evasive-shot', 'Evasive Shot', 'Retreating Shot briefly grants damage avoidance.', 'upgrade', 'support', 'survival', 3, 8, undefined, undefined, ['field-dressing'], 0),
      node('hunter-mara', 'survival', 'apex-survivor', 'Apex Survivor', 'Enter a heightened survival state with speed and recovery.', 'active', 'ultimate', 'survival', 4, 8, 'ability.regeneration', undefined, ['camouflage', 'predator-awareness'], 15),
      node('hunter-mara', 'survival', 'resourceful', 'Resourceful', 'Improve consumable and gathered-material efficiency.', 'passive', 'support', 'survival', 4, 9, undefined, { cooldownRatePercent: 0.06 }, ['camouflage'], 0),
      node('hunter-mara', 'survival', 'natures-recovery', "Nature's Recovery", 'Recover faster outside active combat.', 'passive', 'support', 'survival', 4, 10, undefined, { maximumHealth: 1 }, ['predator-awareness'], 0),
      node('hunter-mara', 'survival', 'first-strike', 'First Strike', 'The first hit from concealment deals increased damage.', 'passive', 'support', 'survival', 4, 11, undefined, { projectileDamagePercent: 0.12 }, ['evasive-shot'], 0),
    ],
  },
  {
    characterId: 'warden', identityTitle: 'Mage', identitySummary: 'A fragile ranged caster who specializes in destruction, battlefield control, or arcane protection.', combatStyle: 'Magic damage · control · protection',
    strengths: ['Highest ability potential', 'Strong area control', 'Powerful defensive utility'],
    paths: [
      path('destruction', 'Destruction', 'Elemental damage, ignition, chains, and spell bursts', 'assault'),
      path('control', 'Control', 'Slows, roots, grouping, and manipulation of combat space', 'control'),
      path('protection', 'Protection', 'Wards, teleportation, party barriers, and spell cycling', 'survival'),
    ],
    nodes: [
      node('warden', 'destruction', 'fire-bolt', 'Fire Bolt', 'Launch a compact fire projectile that can ignite an enemy.', 'active', 'standard-skill', 'assault', 1, 0, 'ability.fire-bolt', undefined, [], 0),
      node('warden', 'destruction', 'arcane-force', 'Arcane Force', 'Increase magical and projectile damage.', 'passive', 'support', 'assault', 2, 0, undefined, { projectileDamagePercent: 0.07 }, ['fire-bolt'], 0),
      node('warden', 'destruction', 'burning-embers', 'Burning Embers', 'Ignition effects last longer.', 'upgrade', 'support', 'assault', 2, 1, undefined, undefined, ['fire-bolt'], 0),
      node('warden', 'destruction', 'chain-lightning', 'Chain Lightning', 'Launch lightning that leaps between nearby enemies.', 'active', 'advanced-skill', 'assault', 3, 0, 'ability.magic-missile', undefined, ['arcane-force'], 0),
      node('warden', 'destruction', 'unstable-power', 'Unstable Power', 'Increase spell damage at the cost of slower recovery.', 'passive', 'support', 'assault', 3, 1, undefined, { attack: 0.1 }, ['arcane-force'], 0),
      node('warden', 'destruction', 'spell-penetration', 'Spell Penetration', 'Offensive magic ignores a portion of enemy protection.', 'passive', 'support', 'assault', 3, 2, undefined, { projectileDamagePercent: 0.08 }, ['burning-embers'], 0),
      node('warden', 'destruction', 'arcane-cataclysm', 'Arcane Cataclysm', 'Trigger a devastating elemental detonation around affected enemies.', 'active', 'ultimate', 'assault', 4, 0, 'ability.shock-burst', undefined, ['chain-lightning', 'unstable-power'], 15),
      node('warden', 'destruction', 'explosive-fire-bolt', 'Explosive Fire Bolt', 'Fire Bolt damages nearby enemies on impact.', 'upgrade', 'support', 'assault', 4, 1, undefined, undefined, ['chain-lightning'], 0),
      node('warden', 'destruction', 'overcharge', 'Overcharge', 'Casting several abilities empowers the next spell.', 'passive', 'support', 'assault', 4, 2, undefined, { attack: 0.12 }, ['unstable-power'], 0),
      node('warden', 'destruction', 'elemental-detonation', 'Elemental Detonation', 'Defeating an affected enemy causes a secondary burst.', 'passive', 'support', 'assault', 4, 3, undefined, { projectileDamagePercent: 0.1 }, ['spell-penetration'], 0),
      node('warden', 'control', 'frost-nova', 'Frost Nova', 'Release a frost burst that damages and slows nearby enemies.', 'active', 'standard-skill', 'control', 1, 1, 'ability.frost-nova', undefined, [], 0),
      node('warden', 'control', 'chilling-presence', 'Chilling Presence', 'Magical attacks apply a minor slow.', 'passive', 'support', 'control', 2, 2, undefined, { cooldownRatePercent: 0.05 }, ['frost-nova'], 0),
      node('warden', 'control', 'deep-freeze', 'Deep Freeze', 'Repeated frost effects can briefly freeze an enemy.', 'upgrade', 'support', 'control', 2, 3, undefined, undefined, ['frost-nova'], 0),
      node('warden', 'control', 'gravity-well', 'Gravity Well', 'Create a field that draws enemies toward its center.', 'active', 'advanced-skill', 'control', 3, 3, 'ability.poison-cloud', undefined, ['chilling-presence'], 0),
      node('warden', 'control', 'controlled-space', 'Controlled Space', 'Deal increased damage to controlled or grouped enemies.', 'passive', 'support', 'control', 3, 4, undefined, { projectileDamagePercent: 0.08 }, ['chilling-presence'], 0),
      node('warden', 'control', 'extended-control', 'Extended Control', 'Control effects last longer.', 'passive', 'support', 'control', 3, 5, undefined, { cooldownRatePercent: 0.08 }, ['deep-freeze'], 0),
      node('warden', 'control', 'absolute-control', 'Absolute Control', 'Lock a large area in suspended time and frost.', 'active', 'ultimate', 'control', 4, 4, 'ability.ice-spear', undefined, ['gravity-well', 'controlled-space'], 15),
      node('warden', 'control', 'shattering-frost', 'Shattering Frost', 'Frozen enemies take bonus damage when the effect ends.', 'upgrade', 'support', 'control', 4, 5, undefined, undefined, ['gravity-well'], 0),
      node('warden', 'control', 'event-horizon', 'Event Horizon', 'Gravity Well becomes larger and lasts longer.', 'upgrade', 'support', 'control', 4, 6, undefined, undefined, ['controlled-space'], 0),
      node('warden', 'control', 'control-vulnerability', 'Control Vulnerability', 'Controlled enemies become more vulnerable to party damage.', 'passive', 'support', 'control', 4, 7, undefined, { attack: 0.08 }, ['extended-control'], 0),
      node('warden', 'protection', 'magic-barrier', 'Magic Barrier', 'Create a temporary personal magical shield.', 'active', 'standard-skill', 'survival', 1, 2, 'ability.shield', undefined, [], 0),
      node('warden', 'protection', 'arcane-ward', 'Arcane Ward', 'Increase health and protective strength.', 'passive', 'support', 'survival', 2, 4, undefined, { maximumHealth: 1 }, ['magic-barrier'], 0),
      node('warden', 'protection', 'efficient-casting', 'Efficient Casting', 'Improve ability cooldown recovery.', 'passive', 'support', 'survival', 2, 5, undefined, { cooldownRatePercent: 0.08 }, ['magic-barrier'], 0),
      node('warden', 'protection', 'protective-field', 'Protective Field', 'Create an area that reduces damage to allies inside it.', 'active', 'advanced-skill', 'survival', 3, 6, 'ability.barrier', undefined, ['arcane-ward'], 0),
      node('warden', 'protection', 'reactive-ward', 'Reactive Ward', 'Taking heavy damage strengthens the next barrier.', 'passive', 'support', 'survival', 3, 7, undefined, { armor: 0.12 }, ['arcane-ward'], 0),
      node('warden', 'protection', 'blink-trigger', 'Blink Trigger', 'Dodging becomes a short magical blink.', 'upgrade', 'support', 'survival', 3, 8, undefined, undefined, ['efficient-casting'], 0),
      node('warden', 'protection', 'archmages-refuge', "Archmage's Refuge", 'Create a powerful sanctuary that shields and restores the party.', 'active', 'ultimate', 'survival', 4, 8, 'ability.heal', undefined, ['protective-field', 'reactive-ward'], 15),
      node('warden', 'protection', 'barrier-pulse', 'Barrier Pulse', 'Magic Barrier knocks enemies back when it breaks.', 'upgrade', 'support', 'survival', 4, 9, undefined, undefined, ['protective-field'], 0),
      node('warden', 'protection', 'shared-ward', 'Shared Ward', 'A portion of personal shielding is shared with nearby allies.', 'passive', 'support', 'survival', 4, 10, undefined, { maximumHealth: 1 }, ['reactive-ward'], 0),
      node('warden', 'protection', 'spell-cycle', 'Spell Cycle', 'Defensive spells empower offense, and offensive spells empower defense.', 'passive', 'support', 'survival', 4, 11, undefined, { cooldownRatePercent: 0.1 }, ['blink-trigger'], 0),
    ],
  },
];
